version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_db_volume:/data/db
    networks:
      - app-network  

  backend-auth:
    build: ./backend/auth
    ports:
      - "4000:4000"
    volumes:
      - ./backend/auth:/app
    depends_on:
      - mongo
    networks:
      - app-network  

volumes:
  mongo_db_volume:

networks:
  app-network:
    driver: bridge  